[package]
name = "bevy_tiled_prototype"
description = "A plugin for rendering tiled maps."
version = "0.1.0"
authors = ["John Mitchell"]
homepage = "https://github.com/StarArawn/bevy_tiled"
repository = "https://github.com/StarArawn/bevy_tiled"
license-file = "LICENSE"
edition = "2018"
exclude = [
    "assets/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"

bevy_type_registry = "0.3"
glam = "0.9"
tiled = "0.9"

# [dependencies.physme]
# version = "0.2"
# git = "https://github.com/walterpie/physme.git"
# branch = "master"

[dependencies.bevy]
version = "0.3"
# git = "https://github.com/bevyengine/bevy.git"
# branch = "master"

# tiled = { git = "https://github.com/mattyhall/rs-tiled" }
